dbt_project:
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      threads: 4
      type: teradata
      host: sdt47039.labs.teradata.com # Update this field with your teradata instance hostname
      schema: automobile_business
      tmode: ANSI
      logmech: TD2
      username:  mt255026
      password:  mt255026
  target: dev
